swagger: "2.0"
info:
  title: Contact Manager API
  description: |
    POOSD Team 20 - Contact Management API

    A RESTful API for user authentication and contact management with the following features:
    - Secure user registration and authentication
    - Full CRUD operations for personal contacts  
    - Search functionality with partial matching
    - Cookie-based persistent authentication
    - User data isolation and secure password handling
  version: '1'
  contact:
    name: POOSD Team 20
    email: th992984@ucf.edu

host: 165.232.128.10
basePath: /api
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

tags:
  - name: Authentication
    description: User authentication and session management
  - name: Contacts
    description: Contact management operations

paths:
  /CheckAuth.php:
    get:
      tags:
        - Authentication
      summary: Check authentication status
      description: Verify if user is authenticated via session cookie
      responses:
        200:
          description: Authentication status
          schema:
            type: object
            properties:
              authenticated:
                type: boolean
              user:
                type: object
                properties:
                  id:
                    type: integer
                  firstName:
                    type: string
                  lastName:
                    type: string
                  userName:
                    type: string
                  email:
                    type: string

  /Logout.php:
    delete:
      tags:
        - Authentication
      summary: User logout
      description: Clear authentication cookie and log user out
      responses:
        200:
          description: Logout response
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message:
                type: string
                example: "Logged out successfully"

  /Login.php:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticate user with username/email and password
      parameters:
        - in: body
          name: loginItem
          description: Login credentials
          required: true
          schema:
            type: object
            required:
              - login
              - password
            properties:
              login:
                type: string
                example: "john_doe"
              password:
                type: string
                example: "mypassword123"
      responses:
        200:
          description: Login response
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
              firstName:
                type: string
                example: "John"
              lastName:
                type: string
                example: "Doe"
              error:
                type: string
                example: ""

  /Register.php:
    post:
      tags:
        - Authentication
      summary: User registration
      description: Register a new user account
      parameters:
        - in: body
          name: registerItem
          required: true
          schema:
            type: object
            required:
              - user_name
              - first_name
              - last_name
              - email
              - password
            properties:
              user_name:
                type: string
                example: "john_doe"
              first_name:
                type: string
                example: "John"
              last_name:
                type: string
                example: "Doe"
              email:
                type: string
                example: "john@example.com"
              password:
                type: string
                example: "mypassword123"
      responses:
        200:
          description: Registration response
          schema:
            type: object
            properties:
              id:
                type: integer
              firstName:
                type: string
              lastName:
                type: string
              error:
                type: string

  /CreateContact.php:
    post:
      tags:
        - Contacts
      summary: Create a new contact
      description: Add a new contact for the authenticated user
      parameters:
        - in: body
          name: contactItem
          required: true
          schema:
            type: object
            required:
              - first_name
              - last_name
            properties:
              first_name:
                type: string
                example: "Jane"
              last_name:
                type: string
                example: "Smith"
              email:
                type: string
                example: "jane.smith@example.com"
              phone_number:
                type: string
                example: "+1-555-123-4567"
      responses:
        200:
          description: Contact creation response
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              contact_id:
                type: integer
              error:
                type: string

  /GetContacts.php:
    get:
      tags:
        - Contacts
      summary: Get all contacts
      description: Retrieve all contacts belonging to the authenticated user
      responses:
        200:
          description: List of contacts
          schema:
            type: object
            properties:
              success:
                type: boolean
              contacts:
                type: array
                items:
                  $ref: "#/definitions/Contact"
              error:
                type: string

  /UpdateContact.php:
    put:
      tags:
        - Contacts
      summary: Update a contact
      description: Update an existing contact
      parameters:
        - in: body
          name: updateItem
          required: true
          schema:
            type: object
            required:
              - contact_id
            properties:
              contact_id:
                type: integer
                example: 5
              first_name:
                type: string
                example: "Jane"
              last_name:
                type: string
                example: "Doe"
              email:
                type: string
                example: "jane.doe@example.com"
              phone_number:
                type: string
                example: "+1-555-987-6543"
      responses:
        200:
          description: Contact update response
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              error:
                type: string

  /DeleteContact.php:
    delete:
      tags:
        - Contacts
      summary: Delete a contact
      description: Delete an existing contact
      parameters:
        - name: contact_id
          in: query
          required: true
          type: integer
          description: ID of the contact to delete
      responses:
        200:
          description: Contact deletion response
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              error:
                type: string

  /SearchContacts.php:
    get:
      tags:
        - Contacts
      summary: Search contacts
      description: Search contacts belonging to the authenticated user
      parameters:
        - name: search_term
          in: query
          required: true
          type: string
          description: Search term
      responses:
        200:
          description: Search results
          schema:
            type: object
            properties:
              success:
                type: boolean
              search_term:
                type: string
              results_count:
                type: integer
              contacts:
                type: array
                items:
                  $ref: "#/definitions/Contact"
              error:
                type: string

definitions:
  Contact:
    type: object
    properties:
      contact_id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      phone_number:
        type: string
      record_created:
        type: string
        format: date
  User:
    type: object
    properties:
      id:
        type: integer
      user_name:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        example: false
      error:
        type: string
        example: "Invalid user credentials"
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
        example: true
      message:
        type: string
        example: "Operation completed successfully"
